### PR TITLE
Correct list and classes for numbers in Bootstrap4

### PR DESCRIPTION
**Pull request by Casmo**
Added classes to the config, removed the initialize function and kept support for sizes.

### CODE REVIEW

**Comment by Casmo** [comment]
Sort() now fails.

**Comment by Holt59** [comment]
Hi, thanks for your contribution. Unfortunately the v4 branch is currently out-of-date... I have made lots of change to the master branch that have not been merged into the v4 so I will probably restart the v4 from scratch when I have time.

**Comment by Casmo** [comment]
Is the master compatible with v4? Give me a heads up when you start and and I'll help you with contributions to v4.

**Comment by Holt59** [comment]
I don't think the master is compatible as it is with the v4. 

I stopped working on the v4 because there were some flaws in the alpha (especially with the layout of horizontal forms... ). I think these issue have been corrected by now, so I will try to merge and update the v4 branch. I'll let you know when the merges are finished. 

Thanks.

**Pull request closed without merging**
