### PR TITLE
Tooltip functionality

### PR DESCRIPTION
**Pull request by ypnos-web**

### CODE REVIEW

**Comment by Holt59** [comment]
I like the idea, but the implementation seems a bit "raw" for me (I like options!), maybe you could use a template or something like this:
```php
public function tooltip($text, $tooltip, $placement = 'right', $options = []) {
    if (is_array($placement)) {
        $options = $placement;
    }
    $options += [
        'tag'            => 'span',
        'data-toggle'    => 'tooltip',
        'data-placement' => $placement,
        'title'          => $tooltip
    ];
    $tag = $options['tag'];
    unset($options['tag']);
    return $this->tag($tag, $text, $options);
}
```

**Comment by raul338** [comment]
I would use this. But set placement as an option instead of parameter

**Comment by Holt59** [comment]
@raul338 Yes, would be better, so something like this:
```php
protected $_defaultTooltipPlacement = "right";

public function tooltip($text, $tooltip, $options = []) {
    $options += [
        'tag'         => 'span',
        'data-toggle' => 'tooltip',
        'placement'   => $this->_defaultTooltipPlacement,
        'title'       => $tooltip
    ];
    $options['data-placement'] = $options['placement'];
    $tag = $options['tag'];
    unset($options['placement'], $options['tag']);
    return $this->tag($tag, $text, $options);
}
```
And use a protected attributes `_defaultTooltipPlacement` which default to e.g. `"right"` but may be set during the intialization of helper (I personally always put my tooltips below, so it is very cool to be able to customze it for the whole site without having to specify it for each tooltip).

**Comment by ypnos-web** [comment]
I really like your suggestions that greatly improve on my first concept. However I think the possibility to inject the tooltip into an existing tag should be retained.

E.g. using it like this: `$this->Html->tooltip($this->Html->button('i:star'), __('Add to Favorites'));` I don't know if a `<span><button /></span>` is what we would always want in that situation.

**Comment by Holt59** [comment]
I see what you want to do but to me something like...
```php
$this->Html->tooltip($this->Form->button('i:star'), __('Add to Favorites'));
```
...seems wrong.

Maybe a better way would be to add an option `tooltip` to some method? Typically:
```php
$this->Html->tooltip($this->Form->submit('i:star'), __('Add to Favorites'));
```
Would produce something very strange since `submit` as its own container so you would be adding tooltip to the container instead of the `input` itself.

It is really easy to add the `tooltip` option to multiple method without duplicating code (see the *easyIcon* behaviour).

**Comment by ypnos-web** [comment]
Ok let me produce a new solution based on all the helpful comments. I do miss easyIcon support in Html->link() btw.

**Comment by Holt59** [comment]
I have added the [`tooltip`](https://github.com/Holt59/cakephp3-bootstrap-helpers/blob/master/src/View/Helper/BootstrapHtmlHelper.php#L219) method to `BootstrapHtmlHelper`, if you are not working on adding the option, I might close this and try by myself when I find time.

**Comment by ypnos-web** [comment]
Looks pretty good!
I didn't have time to get back to this yet and probably won't in the next couple weeks.

**Comment by Holt59** [comment]
I am closing that pull-request for now. Feel free to open a new one if you want to re-submit a working version as discussed in the posts above. Thanks!

**Pull request closed without merging**
