### PR TITLE
Fix input type reset

### PR DESCRIPTION
**Pull request by alphp**
$this->Form->control(__('Reset'), ['type' => reset, class => 'btn btn-default btn-sm']);
Adds to input class form-control.
Before:
`<div class="form-group"><input type="reset" class="form-control btn btn-default btn-sm" value="Reset"></div>`
After:
`<div class="form-group"><input type="reset" class="btn btn-default btn-sm" value="Reset"></div>`

### CODE REVIEW

**Comment by Holt59** [comment]
If you want reset buttons, you need to use `submit`: https://book.cakephp.org/3.0/en/views/helpers/form.html#creating-buttons-and-submit-elements

What do you get with `submit`?

**Comment by alphp** [comment]
If you add the button "manual" then you can use Submit instead of Input.
However, if you use Controls to add several inputs at once, then that is when Control must detect if it is a Reset button.

`$this->Form->controls($fieldset, ['legend' => false]);`

**Comment by Holt59** [comment]
I see what you mean, but in this case it's a CakePHP bug, so you should PR on their side. There are special "handlings" for `submit` in `control()` (and indirectly in `_getInput`) which are not manager for `reset()`, so you should open an issue / submit a PR directly to CakePHP.

**Comment by alphp** [comment]
Workaround finded.
Using "templates" option:
`php
$this->Form->control(__('Reset'), ['type' => reset, 'templates' => ['input' => '<input type="{{type}}"{{attrs}}>'], class => 'btn btn-default btn-sm']);
`

**Pull request closed without merging**
