### PR TITLE
Firsts changes for CakePHP-4.0 support

### PR DESCRIPTION
**Pull request by alphp**
Some changes for CakePHP-4.0 support.
Compatibility with CakePHP-3.8.2 tested.

### CODE REVIEW

**Comment by Holt59** [comment]
Thanks for the PR. Did  you try to add tests for CakePHP 4.0 for Travis? Would be interesting to see which tests fail for CakePHP 4 to make a complete PR.

**Comment by alphp** [comment]
BreadcrumbsHelperTest.php:25
```php
$view = new View();
```
That's produces Router::url thats not work.
I am trying to understand how to create the view for Router: url to work correctly.

**Comment by alphp** [comment]
I think it is better to create a new branch of the plugin that is compatible with CakePHP 4.
It is the best way to keep the code of strange things clean to maintain the compatibility of the CakePHP 3 and 4 tests at the same time.

**Comment by Holt59** [comment]
Thanks for trying. I will probably make a new repository for CakePHP 4, because this one already have branches for Bootstrap 3 & 4.

**Comment by alphp** [comment]
My tests do not require many modifications to make the plugin compatible with CakePHP 4, in addition many of them have backward compatibility with CakePHP 3.
Where I am having more difficulties is with the tests and the date-time type form, which in CakePHP 4 is already a text field.
You can follow my progress in:
https://github.com/fawno/cakephp3-bootstrap-helpers/tree/cakephp-4.0-support
https://travis-ci.org/fawno/cakephp3-bootstrap-helpers

**Pull request closed without merging**
