### PR TITLE
Fix FancyFileWidget

### LINKED ISSUE #123: Problem with SecurityComponent and fancy file control
Hello,

With CakePHP 3.4.x I get the error:

> Unexpected field 'filename-text' in POST data, Unexpected field 'filename.error' in POST data, Unexpected field 'filename.name' in POST data, Unexpected field 'filename.size' in POST data, Unexpected field 'filename.tmp_name' in POST data, Unexpected field 'filename.type' in POST data, Missing field 'filename' in POST data
Cake\Controller\Exception\AuthSecurityException

See https://book.cakephp.org/3.0/en/controllers/components/security.html#form-tampering-prevention

I did not have this problem with Cake 3.3.X. It also works as expected with `useCustomFile` set to false.

My form is very simple:

```php
$formOptions = [
    'horizontal' => true,
    'type' => 'file',
    'url' => ['action' => 'create_attachment', $owner->id],
];

?>
<div class="well">
    <?= $this->Form->create($data, $formOptions) ?>

    <fieldset>
        <legend><?= __("Add new attachment") ?></legend>
        <?php
        echo $this->Form->control('filename', [
            'type' => 'file',
            'preview' => true,
            'label' => __('File'),
        ]);
        echo $this->Form->control('caption', [
            'label' => __('Caption'),
            'rows' => 3
        ]);
        ?>
    </fieldset>
    <?= $this->Form->submit('i:check '.__('Save')) ?>
    <?= $this->Form->end() ?>
</div>
```
The Entity ($data) is also very simple:

```
object(App\Model\Entity\File) {

	'for_model' => 'materials',
	'model_id' => (int) 17550,
	'[new]' => true,
	'[accessible]' => [
		'*' => false,
		'filename' => true,
		'type' => true,
		'size' => true,
		'caption' => true
	],
	'[dirty]' => [
		'for_model' => true,
		'model_id' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Files'

}
```

### PR DESCRIPTION
**Pull request by ypnos-web**
Various fixes for the fancy file upload widget.

To fix #123 and some more problems I found.

### CODE REVIEW

**Comment by ypnos-web** [comment]
A test is failing, I have no idea what is going on there, maybe you have an idea?

**Comment by Holt59** [comment]
I can't look into this right now but quickly looking at the error from travis:

```
1) Bootstrap\Test\TestCase\View\Helper\FormHelperTest::testFormSecuredFileControl
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'Contact.picture-text'
+    0 => 'Contact.picture]-text'
     1 => 'Contact.picture.name'
     2 => 'Contact.picture.type'
     3 => 'Contact.picture.tmp_name'
     4 => 'Contact.picture.error'
     5 => 'Contact.picture.size'
 )
```

Maybe you added a typo somewhere?

**Comment by ypnos-web** [comment]
Yes I got this failure also with phpunit, I don't know where the extra ']' is coming from. I am not as experienced with Cake's templating so I thought I'd ask you first.

I will try to debug the test. In my own use case everything works as expected. That's at least something ;).

**Comment by Holt59** [comment]
I think I got something similar and the beginning, and it's why I switch to the `[text]` field, so the issue might be that you reverted this change... I cannot investigate more right now unfortunately.

**Comment by Holt59** [comment]
@ypnos-web Could you provide me a working example (e.g. from your own use case)? I will see if I can do something about that false phpunit warning.

**Comment by ypnos-web** [comment]
This would be a working example:

```php
    public function testFormSecuredFileControl() {
        $this->form->setConfig('useCustomFileInput', true);
        // Test with filename, see issue #56
        $this->assertEquals([], $this->form->fields);
        $this->form->file('picture');
        $expected = [
            'picture-text',
            'picture.name', 'picture.type',
            'picture.tmp_name', 'picture.error',
            'picture.size'
        ];
        $this->assertEquals($expected, $this->form->fields);
    }

```

**Comment by Holt59** [comment]
@ypnos-web I was talking about a working application (because I did not manage to create one that reproduces everything... ), but if this test fixes the issue, feel free to update the TestCase with it.

**Comment by ypnos-web** [comment]
I rewrote the code to work in both cases. I feared it would bite back at us as soon as someboday actually has the file as a member of another entity.

**Comment by Holt59** [comment]
@ypnos-web Thanks for the update.

Could you merge `testFormSecuredFileControl` and `testFormSecuredFileControl2` (place the 3 asserts in a single `testFormSecuredFileControl`)? If you don't have time, I'll merge and update it myself this week-end.

**Comment by ypnos-web** [comment]
Sorry I didn't spend more time on how I could merge them the first time.

**Comment by Holt59** [comment]
I was actually thinking about simply putting the two `assertEquals` in the same method, but this work, so I'm merging, thanks ;)

**Comment by ypnos-web** [comment]
Well in that case I reckon the form would've needed to be resetted in between, or the second assert include the fields from the first.

**Pull request merged**
