### PR TITLE
4.0.1 alpha

### PR DESCRIPTION
**Pull request by alexdd55**
Added missing return types as cakephp 4.x requested

### CODE REVIEW

**Comment by Holt59** [comment]
Hi @alexdd55, the `4.0.1-alpha` branch is for Bootstrap 4, not CakePHP 4.

**Comment by alexdd55** [comment]
oh, thats a misunderstanding. branch names seems to be very confusing at
this point.
in what branch would it actually fit?

Am Mi., 21. Aug. 2019 um 13:49 Uhr schrieb Mikaël Capelle <
notifications@github.com>:

**Comment by Holt59** [comment]
@alexdd55 I would have to rethink my branch naming for CakePHP 4, maybe c.b.v where `c` is the CakePHP version, `b` the bootstrap and `c` the actual version, e.g., `4.3.1` for CakePHP 4, Bootstrap 3, version 1.

There is an issue with your PR in that you've forked branch `4.0.1-alpha` which is meant for Bootstrap 4, but panels are not in Bootstrap 4, they've been replaced by `Card` (https://github.com/Holt59/cakephp3-bootstrap-helpers/blob/4.0.1-alpha/src/View/Helper/CardHelper.php).

**Comment by alexdd55** [comment]
renaming sounds good 👍👍

i need to check back for that issue, because cake however gave me the error
that panelHelper is needed, so i took it from other branch and the error
was gone

Am Mi., 21. Aug. 2019 um 15:49 Uhr schrieb Mikaël Capelle <
notifications@github.com>:

**Comment by Holt59** [comment]
@alexdd55 Are you using Bootstrap 3 or 4? If you're using Bootstrap 3, you should fork from `master` instead of `4.0.1-alpha`.

**Comment by alexdd55** [comment]
i use bootstrap 4. latest release.

Am Mi., 21. Aug. 2019 um 16:55 Uhr schrieb Mikaël Capelle <
notifications@github.com>:

**Comment by alexdd55** [comment]
found my mistake i made in the first place.
i c&p the helpers, but those are for bootstrap3 (inkl. panels) ... this
might be the reason...
i will kick out the panelHelper and check back after that


Am Mi., 21. Aug. 2019 um 16:55 Uhr schrieb Mikaël Capelle <
notifications@github.com>:

**Comment by Holt59** [comment]
@alexdd55 Then you should not need the `PanelHelper`, Maybe you are simply loading the panel in your `AppView` and not using it, in which case you can simply remove it.

**Pull request closed without merging**
